# Generated by Django 4.1.6 on 2023-03-12 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_brands'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Brands',
        ),
    ]
