# Generated by Django 4.1.6 on 2023-03-14 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dailysheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_id', models.IntegerField()),
                ('date', models.IntegerField()),
                ('brand_name', models.CharField(max_length=50)),
                ('ML', models.IntegerField()),
                ('Opening_bal', models.IntegerField()),
                ('plant', models.IntegerField()),
                ('ob_total', models.IntegerField()),
                ('Closing_bal', models.IntegerField()),
                ('sales', models.IntegerField()),
                ('MR', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='brand',
            name='bid',
        ),
        migrations.AlterModelTable(
            name='brand',
            table='adminapp_brand',
        ),
    ]
