# Generated by Django 4.1.6 on 2023-03-15 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_dailysheet_remove_brand_bid_alter_brand_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailysheet',
            name='id',
        ),
        migrations.RemoveField(
            model_name='dailysheet',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='dailysheet',
            name='timestamp',
        ),
        migrations.AlterField(
            model_name='dailysheet',
            name='d_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dailysheet',
            name='date',
            field=models.DateField(),
        ),
    ]
